name: 2dfan Task Runner

on:
  schedule:
    - cron: '0 22 * * *'  # UTC时间19点对应北京时间6点.
  workflow_dispatch: # 手动触发

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libx11-dev xauth x11vnc fonts-noto-cjk  # 安装中文字体及VNC支持
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Xvfb and VNC server
      run: |
        # 启动 Xvfb 虚拟屏幕
        nohup Xvfb :99 -screen 0 1280x1024x24 &
        export DISPLAY=:99
        
        # 启动 x11vnc 服务器，监听 localhost 并允许连接
        x11vnc -display :99 -nopw -listen localhost -xkb &

    - name: Set DISPLAY and XAUTHORITY environment variables
      run: |
        echo "DISPLAY=:99" >> $GITHUB_ENV
        echo "XAUTHORITY=/home/runner/.Xauthority" >> $GITHUB_ENV
        touch /home/runner/.Xauthority  # 创建一个空的 Xauthority 文件

    - name: Run Python script
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        python 2dfan_DrissionPage.py

    - name: Capture screenshot of virtual screen
      run: |
        # 截取 Xvfb 屏幕并保存为 screenshot.png
        xwd -root -display :99 | convert xwd:- screenshot.png

    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: |
          screenshot.png
          screenshot_detected.png
