name: 2dfan Task Runner

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'  # UTC时间22点对应北京时间6点.
  workflow_dispatch: # 手动触发

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # 缓存 pip 依赖
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get install -y xvfb libx11-dev xauth fonts-noto-cjk  # 安装中文字体
        pip install -r requirements.txt
        
    - name: Start Xvfb
      run: |
        nohup Xvfb :99 -screen 0 1280x1024x24 -ac -nolisten tcp -dpi 96 &
        sleep 3  # 等待 Xvfb 启动完成

    - name: Set DISPLAY and XAUTHORITY environment variables
      run: |
        echo "DISPLAY=:99" >> $GITHUB_ENV
        echo "XAUTHORITY=/home/runner/.Xauthority" >> $GITHUB_ENV
        touch /home/runner/.Xauthority  # 创建空的 Xauthority 文件
        xauth generate :99 . trusted  # 生成 .Xauthority 权限

    - name: Run Python script
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        LOGIN_URL: ${{ secrets.LOGIN_URL }}
      run: |
        python 2dfan_DrissionPage.py

    - name: Check for failure
      if: always()  # 确保此步骤无论之前是否失败都运行
      run: |
        if [ -f "./failure_flag.txt" ]; then
          echo "Sign-in failed, sending email notification..."
          exit 1
        else
          echo "Sign-in succeeded."
        fi
        
    # - name: Upload screenshots as artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: screenshots
    #     path: |
    #       ./screenshot.png
    #       ./screenshot_detected.png
    #       ./pic1.png
    #       ./pic2.png
    #       ./pic3.png
    #       ./pic_error.png